import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxLayout } from "./reduxLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather App Task",
  description: "Generated by create next app",
  icons:{
    icon:""
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxLayout>{children}</ReduxLayout>
      </body>
    </html>
  );
}
